__asm__(
".text \n"
".weak _DYNAMIC \n"
".hidden _DYNAMIC \n"
".global " START " \n"
".type " START ",@function \n"
START ": \n"
"make $fp = 0 \n"
"copyd $r0 = $sp \n"
"andd $sp = $sp, -32 \n"
";; \n"
"pcrel $r1 = @pcrel(_DYNAMIC) \n"
"set $cs = $fp \n"
";; \n"
"goto " START "_c \n"
";; \n"
"errop \n"
";; \n"
);
